remote_theme: yaoyao-liu/minimal-light
title: Chris Anderson
description: Computational Ecology
logo: assets/img/bee.jpg
affiliation_link: https://brosilab.org/people/chris-anderson/
affiliation_logo: assets/img/brosi_logo.png
email: cander20 (at) uw.edu
