theme: jekyll-theme-minimal
title: Chris Anderson
description: Computational Ecologist in the Brosi Lab at UW
logo: assets/img/bee.jpg
logo_link: https://brosilab.org/people/chris-anderson/
email: cander20 (at) uw.edu
